In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split , cross_val_score
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import model_selection
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.linear_model import RidgeCV, LassoCV , ElasticNetCV
from sklearn.model_selection import RepeatedKFold

In [ ]:
df=pd.read_csv("/content/Hitters.csv")
df=df.dropna()

In [ ]:
dms=pd.get_dummies(df[["League","Division","NewLeague"]])

In [ ]:
y=df["Salary"]
X_=df.drop(["Salary","League","Division","NewLeague"],axis=1).astype("float64")
X=pd.concat([X_,dms[["League_N","Division_W","NewLeague_N"]]],axis=1)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [ ]:
enet_model=ElasticNet().fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.488e+06, tolerance: 3.899e+03
  model = cd_fast.enet_coordinate_descent(


In [ ]:
enet_model.coef_

array([ -1.86256172,   8.70489065,   5.10426375,  -2.89875799,
        -1.28642985,   5.24343682,   6.04480276,  -0.14701495,
        -0.21566628,  -0.7897201 ,   1.80813117,   0.80914508,
        -0.61262382,   0.26816203,   0.27172387,  -0.36530729,
        19.2186222 , -31.16586592,   8.98369938])

In [ ]:
enet_model.intercept_

-6.465955602112331

In [ ]:
#Prediction
enet_model.predict(X_train)[0:10]

array([325.74706292, 776.06632333, 522.86508419, 107.64091955,
       449.03139566, 997.76095723,  99.78828622, 311.33763086,
       418.50335021, 879.9502608 ])

In [ ]:
enet_model.predict(X_test)[0:10]

array([ 577.79111731,  617.33202224, 1031.39113156,  364.95861575,
        489.51894393,  300.74185842,  604.522666  ,  465.34678732,
        901.44473965,  703.20357123])

In [ ]:
y_pred=enet_model.predict(X_test)

In [ ]:
np.sqrt(mean_squared_error(y_test,y_pred))

357.1676548181246

In [ ]:
r2_score(y_test,y_pred)

0.41070222469326867

In [ ]:
#Model Tuning

In [ ]:
enet_CV_model=ElasticNetCV(cv=10).fit(X_train,y_train)

In [ ]:
enet_CV_model.alpha_

5230.764736479864

In [ ]:
enet_CV_model.coef_

array([ 0.62845434,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        ,  0.09788752,  0.        ,
        0.27265769,  0.19270075,  0.00758665,  0.3106529 ,  0.        ,
       -0.        ,  0.        , -0.        ,  0.        ])

In [ ]:
enet_CV_model.intercept_

-38.5194055839429

In [ ]:
enet_tuned=ElasticNet(alpha = enet_CV_model.alpha_).fit(X_train,y_train)

In [ ]:
y_pred= enet_tuned.predict(X_test)

In [ ]:
np.sqrt(mean_squared_error(y_test,y_pred))

394.15280563218795

In [ ]:
?ElasticNet