In [1]:
import pandas as pd
df=pd.read_csv("/content/sample_data/california_housing_train.csv")
df=df.iloc[:,:]
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [32]:
X=df.drop('median_house_value', axis=1)
Y=df["median_house_value"]

In [33]:
X.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  
0      1015.0       472.0         1.4936  
1      1129.0       463.0         1.8200  
2       333.0       117.0         1.6509  
3       515.0       226.0         3.1917  
4       624.0       262.0         1.9250

In [34]:
Y.head()

0    66900.0
1    80100.0
2    85700.0
3    73400.0
4    65500.0
Name: median_house_value, dtype: float64

In [35]:
import statsmodels.api as sm

In [36]:
model=sm.OLS(Y,X).fit()

In [37]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:     median_house_value   R-squared (uncentered):                   0.901
Model:                            OLS   Adj. R-squared (uncentered):              0.901
Method:                 Least Squares   F-statistic:                          1.927e+04
Date:                Mon, 07 Oct 2024   Prob (F-statistic):                        0.00
Time:                        18:55:25   Log-Likelihood:                     -2.1492e+05
No. Observations:               17000   AIC:                                  4.298e+05
Df Residuals:                   16992   BIC:                                  4.299e+05
Df Model:                           8                                                  
Covariance Type:            nonrobust                                                  
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
longitude          -2242.3547    119.100    -18.828      0.000   -2475.802   -2008.907
latitude           -8474.2259    377.129    -22.470      0.000   -9213.438   -7735.013
housing_median_age  1786.1485     49.565     36.036      0.000    1688.995    1883.301
total_rooms          -15.3597      0.918    -16.723      0.000     -17.160     -13.559
total_bedrooms        79.9623      8.246      9.697      0.000      63.799      96.125
population           -39.9046      1.277    -31.238      0.000     -42.409     -37.401
households           133.1703      8.918     14.932      0.000     115.689     150.651
median_income       4.584e+04    381.200    120.249      0.000    4.51e+04    4.66e+04
==============================================================================
Omnibus:                     3565.084   Durbin-Watson:                   1.154
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            12369.583
Skew:                           1.040   Prob(JB):                         0.00
Kurtosis:                       6.624   Cond. No.                     3.00e+03
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large,  3e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

Building a model with scikit learn

In [38]:
from sklearn.linear_model import LinearRegression
lm=LinearRegression()

In [39]:
model=lm.fit(X,Y)

In [40]:
model.intercept_

-3620600.892974032

In [41]:
model.coef_

array([-4.31396373e+04, -4.29256731e+04,  1.15069493e+03, -8.37825121e+00,
        1.17648543e+02, -3.84887721e+01,  4.54360026e+01,  4.05070684e+04])

median_house_value= 9954.4+ long *1,4 + lat *1,7+ hous *-2,6+ bet *4,2+ pop* 3,6+ hold *-3,5+ incom *2,8+ value *-6,6

In [42]:
new_datas=[[-114],[34],[15],[1283],[1015],[472],[1.4936],[66900]]

In [43]:
import pandas as pd
new_datas=pd.DataFrame(new_datas).T

In [44]:
new_datas

0     1     2       3       4      5       6        7
0 -114.0  34.0  15.0  1283.0  1015.0  472.0  1.4936  66900.0

In [45]:
model.predict(new_datas)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2.70986854e+09])

In [46]:
import pandas as pd
new_datas=pd.DataFrame(new_datas).T

In [47]:
new_datas

0
0   -114.0000
1     34.0000
2     15.0000
3   1283.0000
4   1015.0000
5    472.0000
6      1.4936
7  66900.0000

In [48]:
from sklearn.metrics import mean_squared_error

In [49]:
MSE=mean_squared_error(Y,model.predict(X))

In [50]:
import numpy as np
RMSE=np.sqrt(MSE)

In [51]:
RMSE

69458.78759326928

In [52]:
X.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  
0      1015.0       472.0         1.4936  
1      1129.0       463.0         1.8200  
2       333.0       117.0         1.6509  
3       515.0       226.0         3.1917  
4       624.0       262.0         1.9250

In [53]:
Y.head()

0    66900.0
1    80100.0
2    85700.0
3    73400.0
4    65500.0
Name: median_house_value, dtype: float64

In [54]:
from sklearn.model_selection import train_test_split

In [66]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [67]:
X_train.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
4622     -118.06     33.78                22.0       4048.0           562.0   
12119    -121.44     38.63                33.0       1077.0           271.0   
3481     -117.90     34.09                34.0       1562.0           272.0   
3152     -117.83     33.68                 4.0       3226.0           838.0   
6895     -118.30     33.75                42.0        967.0           175.0   

       population  households  median_income  
4622       1637.0       541.0         7.3463  
12119       753.0       236.0         1.3462  
3481        825.0       266.0         4.1250  
3152       1666.0       800.0         4.1652  
6895        481.0       163.0         5.6611

In [68]:
Y_train.head()

4622     355600.0
12119     55900.0
3481     220800.0
3152     184500.0
6895     265600.0
Name: median_house_value, dtype: float64

In [69]:
X_test.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
4752     -118.08     33.85                19.0       4261.0           678.0   
13348    -121.93     37.73                23.0       2564.0           347.0   
13459    -121.95     37.32                39.0       1164.0           199.0   
6691     -118.29     34.07                22.0        492.0           269.0   
12750    -121.79     38.66                15.0       6809.0          1052.0   

       population  households  median_income  
4752       2621.0       661.0         6.2427  
13348      1043.0       351.0         6.2048  
13459       619.0       231.0         4.6304  
6691        634.0       261.0         1.6406  
12750      3060.0      1060.0         5.3064

In [70]:
Y_test.head()

4752     288700.0
13348    275000.0
13459    263200.0
6691     300000.0
12750    165000.0
Name: median_house_value, dtype: float64

In [71]:
lm=LinearRegression()

In [72]:
model=lm.fit(X_train,Y_train)

In [74]:
#eğitim hatası
np.sqrt(mean_squared_error(Y_train,model.predict(X_train)))

70096.99776923488

In [75]:
#test hatası
np.sqrt(mean_squared_error(Y_test,model.predict(X_test)))

66901.50820466477

In [76]:
#k-katlı c-v
from sklearn.model_selection import cross_val_score

In [77]:
cross_val_score(model,X_train,Y_train,cv=10,scoring="neg_mean_squared_error")

array([-5.00999709e+09, -4.99165555e+09, -4.71229935e+09, -5.11979452e+09,
       -4.53100854e+09, -4.72255479e+09, -5.58438427e+09, -5.17057988e+09,
       -4.95899347e+09, -4.64676420e+09])

In [78]:
#cv mse
np.mean(-cross_val_score(model,X_train,Y_train,cv=10,scoring="neg_mean_squared_error"))

4944803165.87507

In [79]:
#cv rmse
np.sqrt(np.mean(-cross_val_score(model,X_train,Y_train,cv=10,scoring="neg_mean_squared_error")))

70319.29440683452